### ISSUE TITLE
Feature Request: /tell and /w aliases

### ISSUE THREAD

**Issue by Dymeth** [scruffyboy13/MSG#1]
Please add /tell and /w aliases of /msg command.
Is vanilla aliases of /msg, that provides to bypass /donotdisturb and /ignore.

And there are aliases from EssentialsX:  /msg /w /m /t /pm /emsg /epm /tell /etell /whisper /ewhisper
It might be worth adding support for some of them: /t and /whisper most likely

**Comment by akrentz6** [comment]
Added tell, t, whisper and w aliases. See the spigot page in the next few minutes for an update
